# Generated by Django 5.2.13 on 2026-05-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_feedback_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
