# Generated by Django 5.1.3 on 2026-05-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(upload_to='products/'),
        ),
    ]
